# -*- coding: utf-8 -*-
"""Text Classification OF Bangla New Articles Using RNN (Final NNFLL Project).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9_KBBwTAKWE4BD-U-SIZF21m0W5ykgt
"""

# 0. MOUNT DRIVE (run once)
from google.colab import drive
drive.mount('/content/drive')

# 2. IMPORTS
import pandas as pd
import numpy as np
from collections import Counter
import re
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import StepLR
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import json, time

# 1. PATH TO YOUR CSV
CSV_PATH = "/content/drive/MyDrive/NNFLL/news_dataset.csv"

# 3. LOAD & CLEAN
df = pd.read_csv(CSV_PATH)

def clean_text(t):
    t = re.sub(r'^["\']|["\']$', '', t.strip())
    t = re.sub(r'\n', ' ', t)
    t = re.sub(r'\s+', ' ', t)
    t = re.sub(r'[^\u0980-\u09FF\s.,!?]', '', t)
    return t.strip()

df['clean_text'] = df['text'].apply(clean_text)
df['label'] = df['label'].str.strip().str.lower()

# 4. TOKENISE + VOCAB
MAX_VOCAB = 10_000
MAX_LEN   = 500

def tokenize(txt): return txt.split()

all_words = [w for txt in df['clean_text'] for w in tokenize(txt)]
word_cnt  = Counter(all_words)

vocab = ['<PAD>', '<UNK>'] + [w for w,c in word_cnt.most_common(MAX_VOCAB-2)]
word2idx = {w:i for i,w in enumerate(vocab)}
idx2word = {i:w for w,i in word2idx.items()}

print(f"Vocab size: {len(vocab)}")

# 5. TEXT → INDEX → PADDED
def text_to_seq(txt):
    return [word2idx.get(w, word2idx['<UNK>']) for w in tokenize(txt)]

df['seq'] = df['clean_text'].apply(text_to_seq)

def pad_or_truncate(s, length=MAX_LEN, pad_idx=0):
    if len(s) > length: return s[:length]
    else:               return s + [pad_idx] * (length - len(s))

df['padded'] = df['seq'].apply(lambda x: torch.tensor(pad_or_truncate(x), dtype=torch.long))

# 6. LABEL ENCODING + TRAIN/TEST SPLIT
label2idx = {'economy':0, 'entertainment':1, 'international':2, 'sports':3, 'state':4}
df['label_id'] = df['label'].map(label2idx)

X = df['padded'].tolist()
y = df['label_id'].tolist()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, stratify=y, random_state=42)

print(f"Train: {len(X_train)} | Test: {len(X_test)}")

# 7. DATASET & DATALOADER (FIXED)
class BanglaNewsDataset(Dataset):
    def __init__(self, seqs, labels):
        self.seqs   = seqs
        self.labels = labels
    def __len__(self): return len(self.seqs)
    def __getitem__(self, i):
        return self.seqs[i], torch.tensor(self.labels[i], dtype=torch.long)

train_ds = BanglaNewsDataset(X_train, y_train)
test_ds  = BanglaNewsDataset(X_test,  y_test)

BATCH_SIZE = 32
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False)

# 8. MODEL (RNN / LSTM) – FIXED forward
class RNNClassifier(nn.Module):
    def __init__(self, vocab_sz, embed_dim=128, hidden_dim=256,
                 num_layers=1, dropout=0.3, rnn_type='rnn', n_classes=5):
        super().__init__()
        self.embed = nn.Embedding(vocab_sz, embed_dim, padding_idx=0)

        if rnn_type == 'lstm':
            self.rnn = nn.LSTM(embed_dim, hidden_dim, num_layers,
                               batch_first=True,
                               dropout=dropout if num_layers>1 else 0)
        else:
            self.rnn = nn.RNN(embed_dim, hidden_dim, num_layers,
                              batch_first=True,
                              dropout=dropout if num_layers>1 else 0)

        self.drop = nn.Dropout(dropout)
        self.fc   = nn.Linear(hidden_dim, n_classes)

    def forward(self, x):
        e = self.embed(x)

        if isinstance(self.rnn, nn.LSTM):
            _, (h, _) = self.rnn(e)
        else:
            _, h = self.rnn(e)

        h = h[-1]
        h = self.drop(h)
        return self.fc(h)

# 9. TRAIN / EVAL HELPERS
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Device:", device)

def train_one_epoch(m, loader, crit, opt):
    m.train()
    loss_sum, correct, total = 0, 0, 0
    for seq, lbl in loader:
        seq, lbl = seq.to(device), lbl.to(device)
        opt.zero_grad()
        out = m(seq)
        loss = crit(out, lbl)
        loss.backward()
        opt.step()
        loss_sum += loss.item()
        pred = out.argmax(dim=1)
        correct += (pred == lbl).sum().item()
        total   += lbl.size(0)
    return loss_sum/len(loader), correct/total

def evaluate(m, loader, crit):
    m.eval()
    loss_sum, correct, total = 0, 0, 0
    with torch.no_grad():
        for seq, lbl in loader:
            seq, lbl = seq.to(device), lbl.to(device)
            out = m(seq)
            loss = crit(out, lbl)
            loss_sum += loss.item()
            pred = out.argmax(dim=1)
            correct += (pred == lbl).sum().item()
            total   += lbl.size(0)
    return loss_sum/len(loader), correct/total

# 9. TRAIN / EVAL HELPERS
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Device:", device)

def train_one_epoch(m, loader, crit, opt):
    m.train()
    loss_sum, correct, total = 0, 0, 0
    for seq, lbl in loader:
        seq, lbl = seq.to(device), lbl.to(device)
        opt.zero_grad()
        out = m(seq)
        loss = crit(out, lbl)
        loss.backward()
        opt.step()
        loss_sum += loss.item()
        pred = out.argmax(dim=1)
        correct += (pred == lbl).sum().item()
        total   += lbl.size(0)
    return loss_sum/len(loader), correct/total

def evaluate(m, loader, crit):
    m.eval()
    loss_sum, correct, total = 0, 0, 0
    with torch.no_grad():
        for seq, lbl in loader:
            seq, lbl = seq.to(device), lbl.to(device)
            out = m(seq)
            loss = crit(out, lbl)
            loss_sum += loss.item()
            pred = out.argmax(dim=1)
            correct += (pred == lbl).sum().item()
            total   += lbl.size(0)
    return loss_sum/len(loader), correct/total

# 10. RNNClassifier – works for 1-layer, 2-layer, bidirectional, LSTM/GRU/RNN
class RNNClassifier(nn.Module):
    def __init__(self, vocab_sz, embed_dim=128, hidden_dim=256,
                 num_layers=1, dropout=0.3, rnn_type='rnn',
                 bidirectional=False, n_classes=5):
        super().__init__()
        self.embed = nn.Embedding(vocab_sz, embed_dim, padding_idx=0)
        self.bidir = bidirectional
        self.hidden_dim = hidden_dim * (2 if bidirectional else 1)

        if rnn_type == 'lstm':
            self.rnn = nn.LSTM(embed_dim, hidden_dim, num_layers,
                               batch_first=True,
                               dropout=dropout if num_layers > 1 else 0,
                               bidirectional=bidirectional)
        elif rnn_type == 'gru':
            self.rnn = nn.GRU(embed_dim, hidden_dim, num_layers,
                              batch_first=True,
                              dropout=dropout if num_layers > 1 else 0,
                              bidirectional=bidirectional)
        else:
            self.rnn = nn.RNN(embed_dim, hidden_dim, num_layers,
                              batch_first=True,
                              dropout=dropout if num_layers > 1 else 0,
                              bidirectional=bidirectional)

        self.drop = nn.Dropout(dropout)
        self.fc   = nn.Linear(self.hidden_dim, n_classes)

    def forward(self, x):
        e = self.embed(x)

        if isinstance(self.rnn, nn.LSTM):
            _, (h, _) = self.rnn(e)
        else:
            _, h = self.rnn(e)

        if self.bidir:
            h = torch.cat((h[-2], h[-1]), dim=1)
        else:
            h = h[-1]

        return self.fc(self.drop(h))

# 11. Train one model (with epoch logs + plots)
def train_one_model(name, rnn_type, num_layers=1, bidirectional=False,
                    dropout=0.3, optimizer_type='adam', lr=0.001, epochs=5):
    model = RNNClassifier(len(vocab), rnn_type=rnn_type,
                          num_layers=num_layers, bidirectional=bidirectional,
                          dropout=dropout).to(device)

    opt = optim.Adam(model.parameters(), lr=lr) if optimizer_type == 'adam' else \
          optim.SGD(model.parameters(), lr=lr, momentum=0.9)
    crit = nn.CrossEntropyLoss()
    scheduler = StepLR(opt, step_size=3, gamma=0.5)

    train_l, train_a, val_l, val_a = [], [], [], []

    for epoch in range(1, epochs + 1):
        model.train()
        loss_sum, correct, total = 0, 0, 0
        for seq, lbl in train_loader:
            seq, lbl = seq.to(device), lbl.to(device)
            opt.zero_grad()
            out = model(seq)
            loss = crit(out, lbl)
            loss.backward()
            opt.step()
            loss_sum += loss.item()
            correct += (out.argmax(1) == lbl).sum().item()
            total   += lbl.size(0)
        train_l.append(loss_sum / len(train_loader))
        train_a.append(correct / total)

        model.eval()
        vloss, vcorrect, vtotal = 0, 0, 0
        with torch.no_grad():
            for seq, lbl in test_loader:
                seq, lbl = seq.to(device), lbl.to(device)
                out = model(seq)
                vloss += crit(out, lbl).item()
                vcorrect += (out.argmax(1) == lbl).sum().item()
                vtotal   += lbl.size(0)
        val_l.append(vloss / len(test_loader))
        val_a.append(vcorrect / vtotal)

        scheduler.step()
        print(f"{name} | Epoch {epoch:02d} | "
              f"Train L:{train_l[-1]:.4f} A:{train_a[-1]:.4f} | "
              f"Val   L:{val_l[-1]:.4f} A:{val_a[-1]:.4f}")

    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.plot(train_l, label='Train'); plt.plot(val_l, label='Val')
    plt.title(f'{name} – Loss'); plt.legend()
    plt.subplot(1, 2, 2)
    plt.plot(train_a, label='Train'); plt.plot(val_a, label='Val')
    plt.title(f'{name} – Accuracy'); plt.legend()
    plt.tight_layout()
    plt.show()

    return val_a[-1]

# 12. Run Three Models
print("\n=== Model 1: Basic RNN (1-layer, Adam) ===")
acc1 = train_one_model("M1_RNN", rnn_type='rnn', num_layers=1,
                       bidirectional=False, dropout=0.3,
                       optimizer_type='adam', epochs=5)

print("\n=== Model 2: Bi-LSTM (2-layer, Adam) ===")
acc2 = train_one_model("M2_BiLSTM", rnn_type='lstm', num_layers=2,
                       bidirectional=True, dropout=0.3,
                       optimizer_type='adam', epochs=5)

print("\n=== Model 3: GRU high-dropout (1-layer, SGD) ===")
acc3 = train_one_model("M3_GRU", rnn_type='gru', num_layers=1,
                       bidirectional=False, dropout=0.5,
                       optimizer_type='sgd', epochs=5)

print(f"\nFinal Test Accuracies → M1:{acc1:.4f} | M2:{acc2:.4f} | M3:{acc3:.4f}")

# 1. How Many Layers? (Bi-LSTM, Adam, Dropout=0.3)
exp_name = "EXP1_Layers"
print(f"\n=== {exp_name} ===")
results = []

for nl in [1, 2, 3]:
    acc = train_one_model(f"{exp_name}_L{nl}", rnn_type='lstm', num_layers=nl,
                          bidirectional=True, dropout=0.3,
                          optimizer_type='adam', epochs=6)
    results.append([nl, f"{acc:.4f}"])

df1 = pd.DataFrame(results, columns=["Layers", "Test Acc"])
print(df1.to_markdown(index=False))

# 2. Dropout Regularisation (2-Layer Bi-LSTM)
exp_name = "EXP2_Dropout"
print(f"\n=== {exp_name} ===")
results = []

for do in [0.2, 0.3, 0.5]:
    acc = train_one_model(f"{exp_name}_D{do}", rnn_type='lstm', num_layers=2,
                          bidirectional=True, dropout=do,
                          optimizer_type='adam', epochs=6)
    results.append([do, f"{acc:.4f}"])

df2 = pd.DataFrame(results, columns=["Dropout", "Test Acc"])
print(df2.to_markdown(index=False))

# 3. Optimizer Comparison (2-Layer Bi-LSTM)
exp_name = "EXP3_Optim"
print(f"\n=== {exp_name} ===")
results = []

for opt, lr in [("adam",0.001), ("sgd",0.01), ("rmsprop",0.001)]:
    acc = train_one_model(f"{exp_name}_{opt.upper()}", rnn_type='lstm',
                          num_layers=2, bidirectional=True, dropout=0.3,
                          optimizer_type=opt, lr=lr, epochs=6)
    results.append([opt.upper(), lr, f"{acc:.4f}"])

df3 = pd.DataFrame(results, columns=["Optimizer", "LR", "Test Acc"])
print(df3.to_markdown(index=False))

# 4. Bidirectional Context (GRU, 1-Layer)
exp_name = "EXP4_BiDir"
print(f"\n=== {exp_name} ===")
results = []

for bi in [False, True]:
    acc = train_one_model(f"{exp_name}_Bi{bi}", rnn_type='gru', num_layers=1,
                          bidirectional=bi, dropout=0.3,
                          optimizer_type='adam', epochs=6)
    results.append([str(bi), f"{acc:.4f}"])

df4 = pd.DataFrame(results, columns=["Bidirectional", "Test Acc"])
print(df4.to_markdown(index=False))

# Final Summary (All Best Models)
summary = [
    ["Basic RNN (1L)",          acc1],
    ["Bi-LSTM (2L)",            acc2],
    ["GRU high-drop (1L)",      acc3],
    ["Bi-LSTM (3L) – EXP1",    float(df1.iloc[2,1])],
    ["Dropout 0.3 – EXP2",     float(df2.iloc[1,1])],
    ["Adam – EXP3",            float(df3.iloc[0,2])],
    ["Bi-GRU – EXP4",          float(df4.iloc[1,1])],
]
df_sum = pd.DataFrame(summary, columns=["Model", "Test Acc"])
print(df_sum.to_markdown(index=False))

# Report-Ready Block (Methodology + Training + Results)
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
import random, os

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
print(f"Random seed fixed to {SEED}")

def train_and_log(name, rnn_type, num_layers=1, bidirectional=False,
                  dropout=0.3, optimizer_type='adam', lr=0.001, epochs=6):
    model = RNNClassifier(len(vocab), rnn_type=rnn_type,
                          num_layers=num_layers, bidirectional=bidirectional,
                          dropout=dropout).to(device)

    opt = optim.Adam(model.parameters(), lr=lr) if optimizer_type=='adam' else \
          optim.SGD(model.parameters(), lr=lr, momentum=0.9)
    crit = nn.CrossEntropyLoss()
    scheduler = StepLR(opt, step_size=3, gamma=0.5)

    train_losses, train_accs = [], []
    val_losses,   val_accs   = [], []
    all_preds, all_labels = [], []

    for epoch in range(1, epochs+1):
        model.train()
        loss_sum = correct = total = 0
        for seq, lbl in train_loader:
            seq, lbl = seq.to(device), lbl.to(device)
            opt.zero_grad()
            out = model(seq)
            loss = crit(out, lbl)
            loss.backward()
            opt.step()
            loss_sum += loss.item()
            pred = out.argmax(1)
            correct += (pred == lbl).sum().item()
            total   += lbl.size(0)
        train_losses.append(loss_sum/len(train_loader))
        train_accs.append(correct/total)

        model.eval()
        vloss = vcorrect = vtotal = 0
        epoch_preds, epoch_labels = [], []
        with torch.no_grad():
            for seq, lbl in test_loader:
                seq, lbl = seq.to(device), lbl.to(device)
                out = model(seq)
                vloss += crit(out, lbl).item()
                pred = out.argmax(1)
                vcorrect += (pred == lbl).sum().item()
                vtotal   += lbl.size(0)
                epoch_preds.extend(pred.cpu().numpy())
                epoch_labels.extend(lbl.cpu().numpy())
        val_losses.append(vloss/len(test_loader))
        val_accs.append(vcorrect/vtotal)
        all_preds.extend(epoch_preds)
        all_labels.extend(epoch_labels)

        scheduler.step()
        print(f"{name} | Epoch {epoch:02d} | "
              f"Train L:{train_losses[-1]:.4f} A:{train_accs[-1]:.4f} | "
              f"Val   L:{val_losses[-1]:.4f} A:{val_accs[-1]:.4f}")

    plt.figure(figsize=(12,4))
    plt.subplot(1,2,1); plt.plot(train_losses, label='Train'); plt.plot(val_losses, label='Val')
    plt.title(f'{name} – Loss'); plt.legend()
    plt.subplot(1,2,2); plt.plot(train_accs, label='Train'); plt.plot(val_accs, label='Val')
    plt.title(f'{name} – Accuracy'); plt.legend()
    plt.tight_layout(); plt.show()

    cm = confusion_matrix(all_labels, all_preds)
    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=label2idx.keys(), yticklabels=label2idx.keys())
    plt.title(f'{name} – Confusion Matrix')
    plt.ylabel('True'); plt.xlabel('Predicted')
    plt.show()

    report = classification_report(all_labels, all_preds,
                                   target_names=label2idx.keys(), output_dict=True)
    rep_df = pd.DataFrame(report).transpose().round(4)
    print(rep_df)

    return {
        'test_acc'   : val_accs[-1],
        'cm'         : cm,
        'report_df'  : rep_df,
        'history'    : {'train_loss':train_losses, 'val_loss':val_losses,
                        'train_acc':train_accs,   'val_acc':val_accs}
    }

experiments = [
    ("M1_RNN",      dict(rnn_type='rnn',  num_layers=1, bidirectional=False, dropout=0.3, optimizer_type='adam')),
    ("M2_BiLSTM",   dict(rnn_type='lstm',  num_layers=2, bidirectional=True,  dropout=0.3, optimizer_type='adam')),
    ("M3_GRU",      dict(rnn_type='gru',   num_layers=1, bidirectional=False, dropout=0.5, optimizer_type='sgd',  lr=0.01)),
]

results = {}
for name, cfg in experiments:
    print(f"\n=== {name} ===")
    results[name] = train_and_log(name, **cfg)

methodology = []
for name, cfg in experiments:
    cfg = {**{'epochs':6, 'lr':0.001}, **cfg}
    row = [name,
           cfg['rnn_type'].upper(),
           cfg['num_layers'],
           cfg['bidirectional'],
           cfg['dropout'],
           cfg['optimizer_type'].upper(),
           cfg['lr'],
           cfg['epochs']]
    methodology.append(row)

meth_df = pd.DataFrame(methodology,
        columns=["Model","RNN","Layers","Bi-dir","Dropout","Optimizer","LR","Epochs"])
print("\n=== Methodology (hyper-parameters) ===")
print(meth_df.to_markdown(index=False))

final = []
for name, log in results.items():
    final.append([name,
                  f"{log['test_acc']:.4f}",
                  f"{log['report_df'].loc['weighted avg','f1-score']:.4f}"])
final_df = pd.DataFrame(final, columns=["Model","Test Acc","Weighted F1"])
print("\n=== Final Results ===")
print(final_df.to_markdown(index=False))

print("\n=== Training Environment ===")
print(f"Device      : {device}")
print(f"PyTorch     : {torch.__version__}")
print(f"CUDA avail. : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU         : {torch.cuda.get_device_name(0)}")

# QUICK VERIFICATION: Load the saved model & predict (FIXED PATH)
import torch
import torch.nn as nn
import re
import os

MODEL_PATH = "/content/drive/MyDrive/NNFLL/bangla_news_classifier/best_bigru_model_final.pth"

if not os.path.exists(MODEL_PATH):
    print("File not found! Check these common paths:")
    print("   /content/drive/MyDrive/NNFLL/best_bigru_model_final.pth")
    print("   /content/drive/MyDrive/NNFLL/bangla_news_classifier/best_bigru_model_final.pth")
    raise FileNotFoundError(MODEL_PATH)
else:
    print(f"Found model at: {MODEL_PATH}\n")


class BestBiGRU(nn.Module):
    def __init__(self, vocab_size, embed_dim=128, hidden_dim=256, num_layers=2, num_classes=5, dropout=0.5, bidirectional=True):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.gru = nn.GRU(embed_dim, hidden_dim, num_layers=num_layers,
                          batch_first=True, dropout=dropout if num_layers > 1 else 0,
                          bidirectional=bidirectional)
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden_dim * 2 if bidirectional else hidden_dim, num_classes)

    def forward(self, x):
        x = self.embedding(x)
        x, _ = self.gru(x)
        x = x[:, -1, :]
        x = self.dropout(x)
        return self.fc(x)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = BestBiGRU(vocab_size=len(vocab), embed_dim=128, hidden_dim=256,
                  num_layers=2, num_classes=5, dropout=0.5, bidirectional=True)

model.load_state_dict(torch.load(MODEL_PATH, map_location=device))
model.to(device)
model.eval()

print("Model loaded successfully!\n")

idx2label = {0: 'economy', 1: 'entertainment', 2: 'international', 3: 'sports', 4: 'state'}

def predict_text(text):
    text = re.sub(r'^["\']|["\']$', '', text.strip())
    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'[^\u0980-\u09FF\s.,!?]', '', text).strip()

    tokens = text.split()
    indices = [word2idx.get(w, word2idx.get('<UNK>', 1)) for w in tokens]

    if len(indices) > 500:
        indices = indices[:500]
    else:
        indices += [0] * (500 - len(indices))

    tensor = torch.tensor(indices, dtype=torch.long).unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(tensor)
        prob = torch.softmax(output, dim=1)
        pred_idx = torch.argmax(prob, dim=1).item()
        confidence = prob[0][pred_idx].item()

    return idx2label[pred_idx], confidence


samples = [
    "বাংলাদেশ ক্রিকেট দল আজ ভারতের বিপক্ষে ম্যাচ খেলবে",
    "চলচ্চিত্র অভিনেত্রী শাবনূর নতুন সিনেমায় অভিনয় করছেন",
    "অর্থনীতি মন্ত্রণালয় নতুন বাজেট ঘোষণা করেছে",
    "যুক্তরাষ্ট্রে বন্দুক হামলায় ১০ জন নিহত",
    "ঢাকায় বন্যার কারণে সড়ক যোগাযোগ বন্ধ",
]

print("="*60)
print("PREDICTIONS")
print("="*60)
for text in samples:
    label, conf = predict_text(text)
    short = text[:60] + ("..." if len(text)>60 else "")
    print(f"Text : {short}")
    print(f"   → Predicted : {label.upper():12} | Confidence : {conf:.3f}\n")

